// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihMOokT2BR73tHF7TiWxJNDyGpjcKpvI',
    appId: '1:860154816255:web:3196b428b0e9d541f80eca',
    messagingSenderId: '860154816255',
    projectId: 'moprog-e663d',
    authDomain: 'moprog-e663d.firebaseapp.com',
    storageBucket: 'moprog-e663d.firebasestorage.app',
    measurementId: 'G-H156G8B0VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7XL2uwGlY-EiKd2nkkNb7NZ1UsyBnWs',
    appId: '1:860154816255:android:040ada65f4eecccef80eca',
    messagingSenderId: '860154816255',
    projectId: 'moprog-e663d',
    storageBucket: 'moprog-e663d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzSNlyYvY-CyFk7fZK6UMpaoEKLjZbKR8',
    appId: '1:860154816255:ios:de2d0c66a7c0db68f80eca',
    messagingSenderId: '860154816255',
    projectId: 'moprog-e663d',
    storageBucket: 'moprog-e663d.firebasestorage.app',
    iosBundleId: 'com.example.bumble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzSNlyYvY-CyFk7fZK6UMpaoEKLjZbKR8',
    appId: '1:860154816255:ios:de2d0c66a7c0db68f80eca',
    messagingSenderId: '860154816255',
    projectId: 'moprog-e663d',
    storageBucket: 'moprog-e663d.firebasestorage.app',
    iosBundleId: 'com.example.bumble',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBihMOokT2BR73tHF7TiWxJNDyGpjcKpvI',
    appId: '1:860154816255:web:45181ee485b1c5b0f80eca',
    messagingSenderId: '860154816255',
    projectId: 'moprog-e663d',
    authDomain: 'moprog-e663d.firebaseapp.com',
    storageBucket: 'moprog-e663d.firebasestorage.app',
    measurementId: 'G-0WX8WLG2WQ',
  );
}
